---
- hosts: all
  become: yes
  tasks:

  - name: Set hostname
    hostname:
        name: "{{ inventory_hostname }}"

  - name: Configure HA Proxy
    template: src=haproxy.j2 dest=/etc/haproxy/haproxy.cfg

  - name: Comment out ens33 lines in /etc/network/interfaces
    lineinfile:
        path: /etc/network/interfaces
        state: present
        regexp: '{{item.From}}'
        line: '{{item.To}}'
        backrefs: yes
      
    with_items:
         - { From: '^(allow-hotplug ens33)', To: '#\1'}
         - { From: '^(iface ens33.*$)', To: '#\1'}
         
  - name: Configure UCARP and static addressing
    template: src=ucarp.j2 dest=/etc/network/interfaces.d/ucarp

  - name: Create UCARP systemd file
    template: src=ucarp-service.j2 dest=/etc/systemd/system/ucarp.service

  - name: Add to systemd list
    systemd:
        name: ucarp.service 
        enabled: on 
        daemon_reload: yes
        state: started
        
        