---
- hosts: all
  become: yes
  tasks:
  - name: Backup default Squid config
    copy:
      src: /etc/squid/squid.conf
      dest: /etc/squid/squid.conf.orig
      backup: yes
      remote_src: yes

  - name: Squid config
    template: src=squid.j2 dest=/etc/squid/squid.conf
  
  - name: Allow HA Proxy to bind to non-existing IP
    sysctl:
        name: net.ipv4.ip_nonlocal_bind
        reload: yes 
        state: present
        sysctl_set: yes
        sysctl_file: /etc/sysctl.conf 
        value: 1

  - name: Configure HA Proxy
    template: src=haproxy.j2 dest=/etc/haproxy/haproxy.cfg

  - name: Comment out ens33 lines in /etc/network/interfaces
    lineinfile:
        path: /etc/network/interfaces
        state: present
        regexp: '{{item.From}}'
        line: '{{item.To}}'
        backrefs: yes
      
    with_items:
         - { From: '^(allow-hotplug ens33)', To: '#\1'}
         - { From: '^(iface ens33.*$)', To: '#\1'}
         
  - name: Configure UCARP and static addressing
    template: src=ucarp.j2 dest=/etc/network/interfaces.d/ucarp

  - name: Create UCARP systemd file
    template: src=ucarp-service.j2 dest=/etc/systemd/system/ucarp.service

  - name: Add to systemd list
    systemd:
        name: ucarp.service 
        enabled: on 
        daemon_reload: yes
        state: started

  - name: Start squid
    systemd:
      name: squid
      state: started

  - pause: minutes=2

  - name: start HAproxy
    systemd:
      name: haproxy
      state: started
    
  
        