---
- hosts: all
  gather_facts: no
  become: yes
  become_user: root
  become_method: su

  tasks:
    - name: Remove old known hosts entries
      become: no
      delegate_to: localhost
      known_hosts:
        name: "{{ hostvars[inventory_hostname].ansible_host }}"
        state: absent   

    - name: Deploy to sysadmin
      become: no
      authorized_key:
        user: 'sysadmin' 
        state: present 
        key: "{{ lookup('file', squid_public_key_file ) }}"

    - name: Generate root ssh keys
      openssh_keypair:
        path: /root/.ssh/id_rsa

    - name: install sudo and visudo
      apt:
        name: 'sudo' 
        state: latest
      
    - name: Make sure we have a 'sudo' group
      group:
        name: sudo 
        state: present
    
    - name: Add sudoers users to sudo group
      user: name=sysadmin groups=sudo append=yes state=present 

    - name: Allow 'sudo' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        insertafter: '^.*env_reset'
        line: 'Defaults        lecture="never"'

    - name: Allow 'sudo' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
    
    - name: Add IP info to /etc/issue
      lineinfile:
        dest: /etc/issue
        state: present
        insertafter: '^Debian'
        line: 'IP: \4{ens33}'

    - name: Set delete file wildcard for ssh host keys
      find:
        paths: /etc/ssh
        patterns: "ssh_host*key*"
      register: wildcard_files_to_delete

    - name: Delete ssh host keys
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ wildcard_files_to_delete.files }}"    
    
    - name: Generate new ssh host key
      command: /usr/bin/ssh-keygen -A
      
    - name: Ensure ssh host key known
      become: no
      delegate_to: localhost
      lineinfile:
        dest: ~/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan ' + hostvars[inventory_hostname].ansible_host) }}"

    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"
    
    - name: add to /etc/hosts
      lineinfile:
          dest: /etc/hosts
          state: present
          
          line: "{{ hostvars[item].ansible_host }}  {{ item }}"          
      loop: "{{ groups['squid']}}"
